server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    druid:
      driver-class-name: ${travel.datasource.driver-class-name}
      url: jdbc:mysql://${travel.datasource.host}:${travel.datasource.port}/${travel.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${travel.datasource.username}
      password: ${travel.datasource.password}
  data:
    mongodb:
      database: ${travel.mongodb.database}
      uri: mongodb+srv://${travel.mongodb.user}:${travel.mongodb.password}@${travel.mongodb.cluster}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.travel.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      travel:
        mapper: debug
        service: info
        controller: info

travel:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: traveluser
    user-ttl: 7200000
    user-token-name: token
  alioss:
    endpoint: ${travel.alioss.endpoint}
    access-key-id: ${travel.alioss.access-key-id}
    access-key-secret: ${travel.alioss.access-key-secret}
    bucket-name: ${travel.alioss.bucket-name}
