travel:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: travel_app
    username: root
    password: ${DB_PASSWORD}
  alioss:
    endpoint: oss-us-east-1.aliyuncs.com
    access-key-id: LTAI5tNyjqfXf9VeCMxao1qi
    access-key-secret: ${ALI_CLOUD_ACCESS_KEY_SECRET}
    bucket-name: world-steps
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  mongodb:
    database: travel-app
    user: Admin
#    password: chncFTyFoBrfLUGv
    password: ${MONGODB_PASSWORD}
    cluster: cluster0.ydsuord.mongodb.net
